# Generated by Django 5.1.7 on 2025-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзер пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефон пользователя')),
                ('language_selected', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=15, verbose_name='Выбранный язык')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
