# Generated by Django 5.1.7 on 2025-03-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Тг ид группы')),
                ('course', models.CharField(max_length=150, verbose_name='Курс группы')),
                ('language', models.CharField(max_length=150, verbose_name='Язык группы')),
                ('days', models.CharField(max_length=150, verbose_name='Дни обучения группы')),
                ('time', models.CharField(max_length=150, verbose_name='Время обучения группы')),
                ('is_in_group', models.BooleanField(default=False, verbose_name='Бот в группе')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(verbose_name='Текст поста')),
                ('type', models.CharField(max_length=150, null=True, verbose_name='Тип поста')),
                ('post_tg_id', models.BigIntegerField(verbose_name='Тг ид поста')),
                ('media_group_id', models.BigIntegerField(blank=True, null=True, verbose_name='Ид медиа группы')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Тг ид пользователя')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзер пользователя')),
                ('language_selected', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=15, verbose_name='Выбранный язык')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MediaGroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=150, verbose_name='Тип медиа')),
                ('media_id', models.TextField(verbose_name='Ид медиа файла')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tg_bot.post')),
            ],
            options={
                'verbose_name': 'Файл медиа-группы',
                'verbose_name_plural': 'Файлы медиа-групп',
            },
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_user', models.BooleanField(default=False, verbose_name='Подтверждён пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Администратора',
                'verbose_name_plural': 'Администраторы',
            },
        ),
    ]
