# Generated by Django 5.1.7 on 2025-03-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('offset', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=450, null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('custom_emoji_id', models.CharField(blank=True, max_length=450, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='tg_bot.post', verbose_name='Форматирование текста поста')),
            ],
        ),
    ]
