# Generated by Django 5.1.7 on 2025-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_in_group',
            field=models.BooleanField(default=False, verbose_name='В группе'),
        ),
    ]
