# Generated by Django 5.1.7 on 2025-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
