# Generated by Django 5.1.7 on 2025-03-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_postentities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostEntities',
        ),
    ]
