# Generated by Django 5.1.7 on 2025-03-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_group_is_in_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_group_id', models.BigIntegerField(verbose_name='Ид медиа группы')),
                ('caption', models.TextField(verbose_name='Текст поста')),
                ('media_file_type', models.CharField(max_length=150, verbose_name='Тип медиа')),
                ('media_id', models.TextField(verbose_name='Ид медиа файла')),
            ],
            options={
                'verbose_name': 'Пост медиа-группу',
                'verbose_name_plural': 'Пост медиа-группы',
            },
        ),
    ]
