# Generated by Django 5.1.7 on 2025-03-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_mediagrouppost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediagrouppost',
            name='media_id',
        ),
        migrations.CreateModel(
            name='MediaGroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.TextField(verbose_name='Ид медиа файла')),
                ('media_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tg_bot.mediagrouppost')),
            ],
            options={
                'verbose_name': 'Файл медиа-группы',
                'verbose_name_plural': 'Файлы медиа-групп',
            },
        ),
    ]
