# Generated by Django 5.1.7 on 2025-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_alter_post_post_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
    ]
