# Generated by Django 5.1.7 on 2025-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_id',
            field=models.CharField(blank=True, max_length=455, null=True, verbose_name='Тг ид медиа файла'),
        ),
    ]
