# Generated by Django 5.1.7 on 2025-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_post_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagroupfile',
            name='media_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип медиа'),
        ),
    ]
