# Generated by Django 5.1.7 on 2025-03-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_alter_mediagroupfile_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediagroupfile',
            old_name='media_type',
            new_name='type',
        ),
    ]
