# Generated by Django 5.1.7 on 2025-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_rename_media_type_mediagroupfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sent_to_owner',
            field=models.BooleanField(default=False, verbose_name='Отправлен отправителю'),
        ),
    ]
