# Generated by Django 5.1.7 on 2025-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_post_sent_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_forwarding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перессылка'),
        ),
    ]
