# Generated by Django 5.1.7 on 2025-04-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_post_is_forwarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_tg_id', models.BigIntegerField(verbose_name='Тг ид группы в котором пост')),
                ('message_id', models.BigIntegerField(unique=True, verbose_name='Тг ид поста')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='tg_bot.post')),
            ],
            options={
                'verbose_name': 'Чат в котором пост',
                'verbose_name_plural': 'Чаты в котором посты',
            },
        ),
    ]
