# Generated by Django 5.1.7 on 2025-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_mediagroupfile_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinchat',
            name='media_group',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Медиа группа'),
        ),
    ]
