# Generated by Django 5.1.7 on 2025-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_postinchat_media_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinchat',
            name='media_group',
        ),
        migrations.AddField(
            model_name='postinchat',
            name='media_group_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ид медиа группы'),
        ),
    ]
